#!/bin/bash
git clone git@github.com:sun1211/universe_app.git
git clone git@github.com:sun1211/login_app.git
git clone git@github.com:sun1211/food_app.git
git clone git@github.com:sun1211/welcome_app.git
git clone git@github.com:sun1211/exercise_app.git
git clone git@github.com:sun1211/health_infor.git
git clone git@github.com:sun1211/order_food.git
git clone git@github.com:sun1211/mail_app.git
git clone git@github.com:sun1211/movie_app.git
git clone git@github.com:sun1211/furniture_app.git
git clone git@github.com:sun1211/plant_app.git
git clone git@github.com:sun1211/shopping_app.git
git clone git@github.com:sun1211/furniture_shop_app.git
git clone git@github.com:sun1211/calling_app.git
git clone git@github.com:sun1211/day_night_animation_app.git
git clone git@github.com:sun1211/clock_app.git
git clone git@github.com:sun1211/travel_app.git
git clone git@github.com:sun1211/quiz_app.git
git clone git@github.com:sun1211/commerce_app.git
git clone git@github.com:sun1211/travel_demo_app.git
git clone git@github.com:sun1211/plant_shop.git
git clone git@github.com:sun1211/food_delivery_app.git
git clone git@github.com:sun1211/food_infor_app.git
